name: FishersList
version: '1.0-SNAPSHOT'
main: org.lumbabalumba.fisherslist.FishersList
api-version: 1.19
authors: [ LumbaBalumba ]
description: A simple plugin that shows a list of players who are currently fishing
commands:
  fishers:
    description: Get a list of fishing players
    usage: /fishers
    permission: fisherslist.fisherspermission
